version: 3

tasks:
  compile:
    desc: Compile the PDF
    cmds:
      - tectonic -X build --keep-intermediates --keep-logs
  
  clean:
    desc: Remove logs and bad compilations
    cmds:
      - rm -rf build
  
  upload:
    desc: Upload the PDF to S3
    cmds:
      - aws s3api put-object --bucket gherasim --key cv.pdf --body build/cv/cv.pdf --content-type application/pdf --profile gherasim