[doc]
name = 'bogdan'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'bogdan'
type = 'pdf'
preamble = 'preamble'
postamble = "postamble"
index = 'bogdan'

#[[output]]
#name = 'radu'
#type = 'pdf'
#preamble = 'preamble'
#postamble = "postamble"
#index = 'radu'